### your site title here

title: 6uclz1_blog
baseurl: /6uclz1_blog # name of the repository
email: 6uclz1@gmail.com

highlighter: rouge
markdown: kramdown

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

exclude:
- README.md

paginate: 3 # the number of post per page

gems: [jekyll-seo-tag, jekyll-paginate]
